### ISSUE TITLE
Wont Activate

### ISSUE THREAD

**Issue by MorbidEntree** [esuarezsantana/yourls-edition-logger#2]
When I try and activate the plugin it just shows a blank screen.

I have uploaded the Klogger script as well to the plugin's folder, by the way.

**Comment by esuarezsantana** [comment]
Did you realized there was a typo in the README? I have just fixed it. Sorry for the late response.

**Comment by MorbidEntree** [comment]
What was the typo?

**Comment by pedrordesign** [comment]
I`m having the same problem, still didn`t finded out what`s going on. Help?!

**Comment by chrismunoz** [comment]
I'm having this same issue. The plugin will not activate. I get a blank white screen with a URL of `[baseURL]/admin/plugins.php?action=activate&plugin=edition-logger&nonce=e76a93c20b`

**Comment by gmolop** [comment]
The plugin is outdated in relation to its dependence ([Klogger](https://github.com/katzgrau/KLogger)).
That's why gives you an **Error 500** *(white screen if you have disabled the errors in your server)*

If you need this to work *(and until the plugin is updated or rewritten)*, the latest version wont work, you will have to download a previous version **_(v0.2.0)_** available on the project repository source.

Direct access to working version: https://github.com/katzgrau/KLogger/releases/tag/0.2.0
