### ISSUE TITLE
cannot find Klogger

### ISSUE THREAD

**Issue by alecyu** [esuarezsantana/yourls-edition-logger#3]
while cloning the suggest Klogger package from https://github.com/katzgrau/KLogger, the logger is named "Logger" but plugin requires "KLogger" as well, that will lead the plugin failed

**Comment by pollerto** [comment]
the plugin fails loading even if you reference Logger.php instead of Klogger.php.
You have to load an older version of Klogger, it works fine with the 0.2.0 https://github.com/katzgrau/KLogger/releases/tag/0.2.0 - you will find that the file in the src folder is named Klogger.php instead of just logger.

**Comment by esuarezsantana** [comment]
Thanks @pollerto. I'm not working anymore on this project.
